name: Algolia

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  test:
    name: Algolia Scraper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Index Docs
        uses: darrenjennings/algolia-docsearch-action@master
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        if: env.ALGOLIA_API_KEY != null
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          file: algolia/config.json
