name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - uses: actions/cache@v3
        name: cache nextjs
        with:
          path: packages/guild-website/.next
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx', '**.m[jt]s', '**.mdx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: build website
        run: 'pnpm build && pnpm export'
        working-directory: packages/guild-website

      - name: push to cloudflare pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: guild-dev-website
          directory: packages/guild-website/out

  blogsync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: sync blog to dev.to
        run: 'pnpm sync:blog'
        env:
          DRY_RUN: ${{ github.ref == 'refs/heads/master' }}
        working-directory: packages/blog-sync

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: prettier:check
        run: 'pnpm prettier:check'
