name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - uses: the-guild-org/shared-config/website-cf@main
        name: build and deploy website
        env:
          NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}
          NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY }}
          NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: guild-dev-website
          prId: ${{ github.event.pull_request.number }}
          websiteDirectory: website
          buildScript: pnpm build && pnpm export
          artifactDir: out

  blogsync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: sync blog to dev.to
        run: 'pnpm sync:blog'
        env:
          DRY_RUN: ${{ github.ref != 'refs/heads/master' }}
          DEV_TO_TOKEN: ${{ secrets.DEV_TO_TOKEN }}
        working-directory: packages/blog-sync

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: prettier:check
        run: 'pnpm prettier:check'

  router-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: typecheck
        run: pnpm --filter guild-website-router typecheck
