name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 22
          packageManager: pnpm

      - uses: the-guild-org/shared-config/website-cf@main
        name: build and deploy website
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: guild-dev-website
          prId: ${{ github.event.pull_request.number }}
          websiteDirectory: website
          buildScript: pnpm build && pnpm export
          artifactDir: out

  seo:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: check
        env:
          SEO_ISSUE_LEVEL: error
        working-directory: website
        run: pnpm next build

  blogsync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 21
          packageManager: pnpm

      - name: sync blog to dev.to
        run: 'pnpm sync:blog'
        env:
          DRY_RUN: ${{ github.ref != 'refs/heads/master' }}
          DEV_TO_TOKEN: ${{ secrets.DEV_TO_TOKEN }}
        working-directory: packages/blog-sync

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 21
          packageManager: pnpm

      - name: prettier:check
        run: 'pnpm prettier:check'

  router-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 21
          packageManager: pnpm

      - name: typecheck
        run: pnpm --filter guild-website-router typecheck
